#!/usr/bin/env python3
"""
Legal Document Intelligence Platform — Agentic Summarizer v2.0
================================================================
Multi-agent pipeline implementing the System Prompt v1.0 spec
(Jurisdiction-Aware, Anti-Hallucination Enforced).

ARCHITECTURE:
  Agent 1 — Identifier         (Step 1: classify, authority, parties, condition)
  Agent 2 — OCR/Quality Insp.  (Step 7: flag illegibility, garbled text, missing annexures)
  Agent 3 — Framework Extr.    (Step 2: apply framework A-H to extract structured fields)
  Agent 4 — Module Runner      (Step 3: chronology, issues, clauses, contradictions, risks)
  Agent 5 — Output Formatter   (Step 4: ratio/executive/digest/litigation/headnote/etc.)
  Agent 6 — Source-Grounding   (Steps 5+6: traceability, hallucination scan, banned phrases)

CRITICAL DESIGN: This is a CLOSED-WORLD agent.
  - NO MCP / NO external DB / NO web search
  - The four corners of the document are the only source
  - Every claim must trace back to a paragraph/clause reference
  - Failed grounding triggers automatic retry with stricter context

MODES:
  PRODUCTION: python summarizer_agent_v2.py --port 5003
  TEST:       python summarizer_agent_v2.py --port 5003 --test

ENV REQUIRED:
  SUMMARIZER_GROQ_API_KEY  (preferred) or GROQ_API_KEY (fallback)
  CORS_ORIGINS             (comma-sep; required in production)

REQUIRED DEPS:
  pip install fastapi uvicorn python-dotenv groq PyPDF2 python-docx
  pip install pdfplumber pymupdf pillow pytesseract mammoth  (for OCR/scanned PDFs)

Author: Himesh | Date: May 2026
"""

import os, sys, json, time, asyncio, logging, re
from datetime import datetime
from typing import Dict, List, Any, Optional, Tuple
from contextlib import asynccontextmanager
from io import BytesIO

from fastapi import FastAPI, HTTPException, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
import uvicorn

# Load .env with line-context warning on parse failures
from dotenv import load_dotenv
import warnings as _w
_dotenv_warnings = []
def _capture_dotenv_warning(message, *a, **k):
    _dotenv_warnings.append(str(message))
with _w.catch_warnings():
    _w.simplefilter("always")
    _orig_show = _w.showwarning
    _w.showwarning = _capture_dotenv_warning
    try:
        load_dotenv()
    finally:
        _w.showwarning = _orig_show

if _dotenv_warnings:
    for w in _dotenv_warnings:
        print(f"[WARN] dotenv: {w}", file=sys.stderr)
        m = re.search(r"line (\d+)", w)
        if m and os.path.exists(".env"):
            ln = int(m.group(1))
            try:
                with open(".env", "r", encoding="utf-8", errors="replace") as f:
                    lines = f.readlines()
                if 0 < ln <= len(lines):
                    print(f"[WARN] dotenv: line {ln} reads: {lines[ln-1].rstrip()!r}", file=sys.stderr)
            except Exception: pass

from groq import Groq

# ── Logging ──────────────────────────────────────────────────────────────
logger = logging.getLogger("summarizer_agent")
logger.setLevel(logging.INFO)
if not logger.handlers:
    _h = logging.StreamHandler(sys.stderr)
    _h.setFormatter(logging.Formatter("[%(levelname)s] %(message)s"))
    logger.addHandler(_h)
logger.propagate = False

# ── Config ───────────────────────────────────────────────────────────────
GROQ_API_KEY = os.getenv("SUMMARIZER_GROQ_API_KEY") or os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    print("ERROR: SUMMARIZER_GROQ_API_KEY or GROQ_API_KEY not set", file=sys.stderr)
    sys.exit(1)

# TEST_MODE detection at module load (uvicorn re-imports the module)
if "--test" in sys.argv:
    os.environ["SUMMARIZER_TEST_MODE"] = "true"
TEST_MODE = os.getenv("SUMMARIZER_TEST_MODE", "false").lower() == "true"

# Model selection
IDENTIFIER_MODEL  = "llama-3.3-70b-versatile"
EXTRACTOR_MODEL   = "llama-3.3-70b-versatile"
MODULE_MODEL      = "llama-3.3-70b-versatile"
FORMATTER_MODEL   = "llama-3.3-70b-versatile"
VERIFIER_MODEL    = "qwen/qwen3-32b"

MAX_DOC_CHARS = 80000           # cap for one LLM call (~30 page judgment)
MAX_RETRY_LOOPS = 1             # source-grounding retry budget

DISCLAIMER_TEXT = (
    "This analysis has been generated by an AI Legal Document Intelligence Platform "
    "applying strict source-grounding rules. All findings are extracted from the uploaded "
    "document only \u2014 no external case laws, statutes, or facts have been imported. "
    "For reliance in court proceedings, appellate filings, or advisory work, please "
    "verify all extracted citations, dates, amounts, and conclusions against the "
    "original document. The platform and its provider disclaim liability for any "
    "consequences arising from use of this output without independent verification."
)


# ══════════════════════════════════════════════════════════════════════════
# FRAMEWORK CATALOG (Step 2: A-H)
# ══════════════════════════════════════════════════════════════════════════

FRAMEWORKS = {
    "A": {
        "name": "Judicial Orders, Judgments & Case Laws",
        "applies_to": "Supreme Court / High Court / Tribunal / Appellate Authority / DRT / NCLT / SAT / ITAT / CESTAT / Consumer Forum",
        "fields": [
            "court_and_bench", "case_citation", "case_title", "nature_of_proceeding",
            "previous_proceedings", "date_of_judgment", "legal_issues_framed",
            "material_facts", "statutory_provisions_invoked", "arguments_appellant",
            "arguments_respondent", "evidence_relied_upon", "judicial_analysis_reasoning",
            "precedents_cited_by_court", "ratio_decidendi", "obiter_dicta",
            "final_decision_held", "operative_directions", "dissenting_opinion",
            "limitation_jurisdictional_notes", "litigation_impact",
        ],
    },
    "B": {
        "name": "Agreements, Contracts, Deeds & Commercial Documents",
        "applies_to": "Sale Deeds, Lease Agreements, Loan Agreements, MOU, JV, Employment, NDA, SPA, Mortgage Deeds",
        "fields": [
            "parties", "execution_date_effective_date", "recitals_background",
            "subject_matter", "obligations_party_a", "obligations_party_b",
            "payment_terms", "representations_warranties", "conditions_precedent",
            "indemnity_clauses", "liability_limitations", "intellectual_property",
            "confidentiality", "termination", "dispute_resolution",
            "governing_law_jurisdiction", "unusual_non_standard_clauses",
            "contradictory_provisions", "hidden_high_risk_provisions",
            "missing_standard_provisions", "compliance_implications",
            "stamp_duty_registration",
        ],
    },
    "C": {
        "name": "Tax Notices, Assessment Orders & Regulatory Proceedings",
        "applies_to": "IT Assessment Orders, Scrutiny/148/148A Notices, SCNs, Adjudication Orders under Customs/GST/Service Tax/FEMA/SEBI, Penalty Orders, Demand Notices",
        "fields": [
            "issuing_authority", "assessee_noticee", "assessment_year_period",
            "date_of_issue_service", "statutory_provisions_invoked",
            "nature_of_proceedings", "allegations_additions_disallowances",
            "tax_demand_quantified", "evidence_relied_upon", "procedural_history",
            "limitation_analysis", "procedural_defects", "opportunities_provided",
            "findings_of_fact", "legal_findings", "order_direction",
            "appeal_rights_mentioned", "suggested_action_points",
            "litigation_risk_indicators",
        ],
    },
    "D": {
        "name": "Petitions, Plaints, Applications & Legal Notices",
        "applies_to": "Writ Petitions, Civil Suits, Arbitration Petitions, Legal Notices, Demand Letters, Consumer Complaints",
        "fields": [
            "nature_and_forum", "parties", "legal_basis", "facts_as_pleaded",
            "reliefs_sought", "interim_reliefs_sought", "urgency_stay_grounds",
            "limitation_compliance", "jurisdictional_basis", "documents_annexed",
            "legal_notices_demand",
        ],
    },
    "E": {
        "name": "Affidavits, Statutory Declarations & Sworn Statements",
        "applies_to": "Affidavits, Statutory Declarations, Sworn Statements",
        "fields": [
            "deponent", "sworn_before", "date", "purpose_context",
            "statements_made", "admissions_concessions", "attachments_referred",
            "legally_significant_declarations",
        ],
    },
    "F": {
        "name": "Wills, Testamentary Documents & Succession Instruments",
        "applies_to": "Wills, Codicils, Testamentary Trusts, Succession Instruments",
        "fields": [
            "testator", "date_of_execution", "witnesses", "assets_covered",
            "beneficiaries", "specific_bequests", "residuary_estate",
            "executor_named", "conditions_on_bequests", "revocation_of_prior_wills",
            "ambiguities_conflicting_provisions",
        ],
    },
    "G": {
        "name": "Circulars, Notifications, Government Orders & Statutory Instruments",
        "applies_to": "CBIC/CBDT Circulars, Notifications, Government Orders, RBI/SEBI Circulars, Statutory Instruments",
        "fields": [
            "issuing_authority", "reference_number_date", "subject", "effective_date",
            "statutory_basis", "key_provisions_changes", "entities_transactions_covered",
            "compliance_requirements", "exemptions_carve_outs",
            "supersession_amendment", "operational_implications",
        ],
    },
    "H": {
        "name": "Legal Commentary, Treatise Chapters & Academic Material",
        "applies_to": "Treatise Chapters, Journal Articles, Legal Commentary, Academic Material",
        "fields": [
            "author_publication", "subject_chapter_title", "core_legal_proposition",
            "statutes_discussed", "cases_cited", "key_legal_principles",
            "areas_of_controversy", "authors_conclusions", "practical_guidance",
        ],
    },
}

# Output formats (Step 4)
OUTPUT_FORMATS = {
    "one_line_ratio": "Single sentence \u2014 the binding legal proposition (judgments only)",
    "executive_summary": "5-7 lines \u2014 key outcome, parties, operative direction",
    "concise_professional": "1-2 paragraphs \u2014 for professional communication",
    "detailed_digest": "Full structured analysis using the applicable framework (DEFAULT)",
    "litigation_note": "Issue \u2192 argument \u2192 finding \u2192 outcome format",
    "issue_wise": "Numbered issues with findings \u2014 appellate strategy",
    "headnote": "Court-publication style headnote (judgments only)",
    "clause_table": "Tabular clause extraction (contracts/deeds)",
    "risk_report": "Risk register with clause references",
    "chronology": "Date-event timeline",
    "advisory": "Action-oriented summary",
    "tabular": "Key data points in table format",
}

# User shortcut command map
USER_SHORTCUTS = {
    "one-liner": "one_line_ratio", "oneliner": "one_line_ratio", "ratio": "one_line_ratio",
    "summary": "concise_professional",
    "full analysis": "detailed_digest", "full": "detailed_digest", "detailed": "detailed_digest",
    "chronology": "chronology", "timeline": "chronology",
    "issues": "issue_wise", "issue-wise": "issue_wise", "issuewise": "issue_wise",
    "clauses": "clause_table", "clause table": "clause_table",
    "contradictions": "_module_contradictions", "conflicts": "_module_contradictions",
    "risks": "risk_report", "risk register": "risk_report", "risk": "risk_report",
    "litigation note": "litigation_note", "litigation": "litigation_note",
    "advisory": "advisory",
    "table": "tabular", "tabular": "tabular",
    "headnote": "headnote",
    "executive": "executive_summary", "executive summary": "executive_summary",
}

# Banned hedge phrases (Step 6 hallucination prevention)
BANNED_PHRASES = [
    r"\btypically\b", r"\bgenerally(?! held)\b", r"\bin practice\b",
    r"\bas a rule\b", r"\bordinarily\b", r"\busually\b",
    r"\bit is well[-\s]?settled\b", r"\bsettled law\b",
    r"\bit is common knowledge\b", r"\bit is well known\b",
]


# ══════════════════════════════════════════════════════════════════════════
# DOCUMENT EXTRACTORS (mirrors notice agent v2.5+)
# ══════════════════════════════════════════════════════════════════════════

def extract_text_from_pdf(content) -> Tuple[str, str]:
    """Cascading PDF extraction. Returns (text, ocr_quality)
    where ocr_quality is High/Moderate/Poor/NotOCR/Failed."""
    errors = []
    best = ""

    try:
        import PyPDF2
        reader = PyPDF2.PdfReader(BytesIO(content))
        if reader.is_encrypted:
            try: reader.decrypt("")
            except Exception: pass
        t = "\n".join((p.extract_text() or "") for p in reader.pages).strip()
        if len(t) >= 500: return t, "NotOCR"
        if len(t) > len(best): best = t
        errors.append(f"PyPDF2: short ({len(t)} chars)")
    except Exception as e:
        errors.append(f"PyPDF2: {type(e).__name__}: {e}")

    try:
        import pdfplumber
        with pdfplumber.open(BytesIO(content)) as pdf:
            t = "\n".join((p.extract_text() or "") for p in pdf.pages).strip()
        if len(t) >= 500: return t, "NotOCR"
        if len(t) > len(best): best = t
        errors.append(f"pdfplumber: short ({len(t)} chars)")
    except ImportError: errors.append("pdfplumber not installed")
    except Exception as e: errors.append(f"pdfplumber: {type(e).__name__}: {e}")

    try:
        import fitz
        doc = fitz.open(stream=content, filetype="pdf")
        t = "\n".join(page.get_text() for page in doc).strip()
        doc.close()
        if len(t) >= 500: return t, "NotOCR"
        if len(t) > len(best): best = t
        errors.append(f"fitz: short ({len(t)} chars)")
    except ImportError: errors.append("PyMuPDF not installed")
    except Exception as e: errors.append(f"fitz: {type(e).__name__}: {e}")

    # OCR fallback with quality assessment
    try:
        import fitz
        from PIL import Image
        import pytesseract
        doc = fitz.open(stream=content, filetype="pdf")
        ocr_pages = []
        confidences = []
        for i, page in enumerate(doc):
            if i >= 30: break
            pix = page.get_pixmap(dpi=200)
            img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)
            try:
                t = pytesseract.image_to_string(img, lang="eng+hin")
            except pytesseract.TesseractError:
                t = pytesseract.image_to_string(img, lang="eng")
            if t.strip():
                ocr_pages.append(t)
                alnum_ratio = sum(1 for c in t if c.isalnum() or c.isspace()) / max(1, len(t))
                confidences.append(alnum_ratio)
        doc.close()
        if ocr_pages:
            full_text = "\n\n--- PAGE BREAK ---\n\n".join(ocr_pages)
            avg_conf = sum(confidences) / max(1, len(confidences))
            if avg_conf >= 0.92: quality = "High"
            elif avg_conf >= 0.80: quality = "Moderate"
            else: quality = "Poor"
            return full_text, quality
        errors.append("OCR: no text on any page")
    except ImportError as ie:
        errors.append(f"OCR unavailable ({ie})")
    except Exception as e:
        errors.append(f"OCR: {type(e).__name__}: {e}")

    if best:
        return best + f"\n\n[Warning: Extraction incomplete. Tried: {'; '.join(errors[:3])}]", "Poor"
    return f"[PDF extraction failed. Tried: {' | '.join(errors[:4])}]", "Failed"


def extract_text_from_docx(content) -> Tuple[str, str]:
    try:
        import docx
        doc = docx.Document(BytesIO(content))
        paras = [p.text for p in doc.paragraphs if p.text.strip()]
        for table in doc.tables:
            for row in table.rows:
                cells = [c.text.strip() for c in row.cells if c.text.strip()]
                if cells: paras.append(" | ".join(cells))
        t = "\n".join(paras).strip()
        if t: return t, "NotOCR"
    except Exception as e:
        try:
            import mammoth
            r = mammoth.extract_raw_text(BytesIO(content))
            t = (r.value or "").strip()
            if t: return t, "NotOCR"
            return f"[DOCX error: python-docx={e}; mammoth: empty]", "Failed"
        except Exception as e2:
            return f"[DOCX error: python-docx={e}; mammoth={e2}]", "Failed"
    return "[DOCX error: empty document]", "Failed"


def extract_text_from_txt(content) -> Tuple[str, str]:
    try: return content.decode("utf-8"), "NotOCR"
    except: return content.decode("latin-1"), "NotOCR"


# ══════════════════════════════════════════════════════════════════════════
# PARAGRAPH ANCHORING (citation traceability)
# ══════════════════════════════════════════════════════════════════════════

def anchor_document(text: str) -> Tuple[str, Dict[int, str]]:
    """Insert [\u00b6N] anchors into the text for precise citation. Returns
    (anchored_text, anchor_map) where anchor_map[N] is the first 200 chars
    of paragraph N (for verifier matching)."""
    if not text: return text, {}
    raw_paras = re.split(r'\n\s*\n', text)
    anchored = []
    anchor_map = {}
    pn = 0
    for p in raw_paras:
        p = p.strip()
        if not p: continue
        pn += 1
        anchored.append(f"[\u00b6{pn}] {p}")
        anchor_map[pn] = p[:200]
    return "\n\n".join(anchored), anchor_map


def detect_paragraph_refs(output: str) -> List[int]:
    refs = set()
    for m in re.finditer(r'\[?\u00b6\s*(\d{1,4})\]?', output):
        refs.add(int(m.group(1)))
    for m in re.finditer(r'\b[Pp]ara(?:graph)?\s*(\d{1,4})\b', output):
        refs.add(int(m.group(1)))
    return sorted(refs)


# ══════════════════════════════════════════════════════════════════════════
# AGENT 1 — IDENTIFIER (Step 1)
# ══════════════════════════════════════════════════════════════════════════

async def identify_document(groq_client, doc_text: str, ocr_quality: str) -> Dict[str, Any]:
    t0 = time.time()
    sample = doc_text[:12000]

    system = """You are a legal document classifier for Indian and international legal frameworks.
Analyse the provided document text and produce a structured classification.

CRITICAL: All values must come from the document. If a field is not stated, return the literal
string "NOT MENTIONED IN DOCUMENT" \u2014 never guess, never infer beyond direct textual support.

Return JSON ONLY with these exact keys:
{
  "document_type": "e.g., 'High Court Judgment', 'Income Tax Assessment Order', 'Sale Deed', 'SCN', 'Arbitration Award', 'Affidavit', 'Will', 'Circular', 'Notification', 'Writ Petition', 'Lease Deed', 'Tribunal Order', 'Commercial Contract', 'Legal Commentary', or 'Other'",
  "issuing_authority": "Court / Tribunal / Authority / Party / Ministry \u2014 as appearing in document",
  "jurisdiction": "as stated in document",
  "document_date": "as stated; or 'NOT MENTIONED IN DOCUMENT'",
  "parties": ["list of parties as named"],
  "subject_matter": "one-line factual description from document",
  "applicable_law": ["statutes/rules/regulations cited in document"],
  "document_condition": "Clear Digital / Scanned with OCR Issues / Multi-part with Annexures / Legibility Concerns",
  "framework_code": "single letter A/B/C/D/E/F/G/H matching the document type",
  "framework_rationale": "one sentence explaining the framework choice",
  "is_hybrid": false,
  "secondary_framework": null
}

FRAMEWORK MAPPING:
  A \u2014 Judicial Orders, Judgments, Tribunal/Appellate decisions
  B \u2014 Agreements, Contracts, Deeds (commercial, property, employment)
  C \u2014 Tax Notices, Assessment Orders, Regulatory Proceedings
  D \u2014 Petitions, Plaints, Applications, Legal Notices
  E \u2014 Affidavits, Statutory Declarations, Sworn Statements
  F \u2014 Wills, Testamentary Documents, Succession Instruments
  G \u2014 Circulars, Notifications, Government Orders, Statutory Instruments
  H \u2014 Legal Commentary, Treatise Chapters, Academic Material

If the document fits two frameworks (e.g., an appellate order that is also a tax adjudication),
set is_hybrid=true and secondary_framework to the second letter."""

    user_prompt = (f"OCR Quality of source: {ocr_quality}\n\n"
                   f"Document text (first 12,000 chars):\n\n{sample}")
    try:
        resp = groq_client.chat.completions.create(
            model=IDENTIFIER_MODEL,
            messages=[{"role":"system","content":system},
                      {"role":"user","content":user_prompt}],
            temperature=0.05, max_tokens=900)
        raw = resp.choices[0].message.content.strip()
        if "</think>" in raw: raw = raw.split("</think>")[-1].strip()
        s, e = raw.find("{"), raw.rfind("}")+1
        ident = json.loads(raw[s:e]) if s>=0 and e>s else {}
    except Exception as ex:
        logger.warning(f"Identifier failed: {ex}")
        ident = {}

    fw = (ident.get("framework_code") or "A").strip().upper()
    if fw not in FRAMEWORKS: fw = "A"
    ident.setdefault("document_type", "Other")
    ident.setdefault("issuing_authority", "NOT MENTIONED IN DOCUMENT")
    ident.setdefault("jurisdiction", "NOT MENTIONED IN DOCUMENT")
    ident.setdefault("document_date", "NOT MENTIONED IN DOCUMENT")
    ident.setdefault("parties", [])
    ident.setdefault("subject_matter", "NOT MENTIONED IN DOCUMENT")
    ident.setdefault("applicable_law", [])
    ident["framework_code"] = fw
    ident["framework_name"] = FRAMEWORKS[fw]["name"]
    ident["ocr_quality"] = ocr_quality
    ident["identify_time_ms"] = int((time.time()-t0)*1000)
    logger.info(f"[Agent 1] type={ident['document_type']} | framework={fw} | "
                f"OCR={ocr_quality} | {ident['identify_time_ms']}ms")
    return ident


# ══════════════════════════════════════════════════════════════════════════
# AGENT 2 — OCR/QUALITY INSPECTOR (Step 7)
# ══════════════════════════════════════════════════════════════════════════

def inspect_document_quality(doc_text: str, ocr_quality: str) -> Dict[str, Any]:
    issues = []
    garbled = []

    if ocr_quality == "Failed":
        issues.append({"type": "EXTRACTION_FAILED", "severity": "CRITICAL",
                       "note": "PDF extraction failed entirely \u2014 analysis cannot proceed."})
    elif ocr_quality == "Poor":
        issues.append({"type": "OCR_QUALITY_POOR", "severity": "HIGH",
                       "note": "OCR produced text with low alphanumeric ratio \u2014 many sections may be misread."})
    elif ocr_quality == "Moderate":
        issues.append({"type": "OCR_QUALITY_MODERATE", "severity": "MEDIUM",
                       "note": "OCR usable but verify critical figures/names/dates against original."})

    # Garbled text detection
    for m in re.finditer(r'\b[A-Za-z]*[^\w\s]{3,}[A-Za-z]*\b', doc_text):
        s = m.group(0)
        if 5 < len(s) < 60:
            garbled.append(s)
            if len(garbled) >= 10: break
    if garbled:
        issues.append({"type": "GARBLED_STRINGS", "severity": "MEDIUM",
                       "note": f"Found {len(garbled)} potentially garbled string(s)",
                       "samples": garbled[:5]})

    # Annexure references
    annex_refs = set()
    for m in re.finditer(r'\b[Aa]nnex(?:ure)?\s*[\-\u2013]?\s*([A-Z0-9]+)\b', doc_text):
        annex_refs.add(m.group(1).upper())
    if annex_refs:
        present = set()
        for a in annex_refs:
            if re.search(rf'^\s*[Aa]nnex(?:ure)?\s*[\-\u2013]?\s*{re.escape(a)}\s*[:\-]?\s*$',
                         doc_text, re.MULTILINE):
                present.add(a)
        missing = annex_refs - present
        if missing:
            issues.append({"type": "ANNEXURES_REFERENCED_NOT_ATTACHED",
                           "severity": "MEDIUM",
                           "note": f"Document references {len(missing)} annexure(s) that may not be attached",
                           "annexures": sorted(missing)})

    # Page-break sanity (OCR mode)
    illegible = []
    if "--- PAGE BREAK ---" in doc_text:
        pages = doc_text.split("--- PAGE BREAK ---")
        for i, p in enumerate(pages, 1):
            if len(p.strip()) < 30 and i < len(pages):
                illegible.append(i)
        if illegible:
            issues.append({"type": "PAGES_NEAR_EMPTY", "severity": "HIGH",
                           "note": f"{len(illegible)} page(s) had very little extracted text",
                           "pages": illegible[:10]})

    if len(doc_text) < 500:
        issues.append({"type": "DOCUMENT_TOO_SHORT", "severity": "CRITICAL",
                       "note": f"Document text is only {len(doc_text)} chars \u2014 likely extraction failure."})

    sev_rank = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3}
    issues.sort(key=lambda i: sev_rank.get(i.get("severity"), 9))
    logger.info(f"[Agent 2] {len(issues)} quality issue(s) | OCR={ocr_quality}")
    return {"ocr_quality": ocr_quality, "issues": issues}


# ══════════════════════════════════════════════════════════════════════════
# AGENT 3 — FRAMEWORK EXTRACTOR (Step 2)
# ══════════════════════════════════════════════════════════════════════════

async def extract_framework_fields(groq_client, doc_text: str,
                                   identification: Dict[str, Any]) -> Dict[str, Any]:
    t0 = time.time()
    fw = identification["framework_code"]
    fields = FRAMEWORKS[fw]["fields"]
    fw_name = FRAMEWORKS[fw]["name"]
    field_specs = "\n".join(f"  - {f}" for f in fields)

    system = f"""You are a legal document field extractor applying Framework {fw} ({fw_name}).

ABSOLUTE RULES (NON-NEGOTIABLE):
1. Extract ONLY what is expressly stated in the document. Never infer, never paraphrase legal conclusions.
2. For each field, cite paragraph references like [\u00b65], [\u00b612], or list multiple as [\u00b65, \u00b612].
3. If a field is not present in the document, return "NOT MENTIONED IN DOCUMENT" \u2014 do not guess.
4. For operative findings, holdings, orders \u2014 reproduce VERBATIM where critical, with [\u00b6N] anchor.
5. Do NOT import external case laws, statutes, or facts that are not in the document.
6. Banned phrases: "typically", "generally", "in practice", "it is well-settled". These signal inferred content.

EXTRACTION FIELDS for Framework {fw}:
{field_specs}

Return JSON ONLY with each field name as a key. Each value should be either:
  (a) A string containing the extracted content + paragraph anchor(s), OR
  (b) An array of strings (for fields with naturally multiple items), OR
  (c) The literal string "NOT MENTIONED IN DOCUMENT"

EXAMPLE (Framework A):
{{
  "court_and_bench": "Hon'ble High Court of Delhi, Coram: J. R.K. Sharma [\u00b61]",
  "case_citation": "W.P.(C) 1234/2024 [\u00b61]",
  "ratio_decidendi": "Where supplier defaults in remitting tax, recipient cannot be denied ITC if conditions of Section 16(2)(a)(b)(d) are met [\u00b645].",
  "precedents_cited_by_court": [
    "Mohit Minerals (P) Ltd. v. UOI, 2022 SCC OnLine SC 657 [\u00b632]"
  ],
  "dissenting_opinion": "NOT MENTIONED IN DOCUMENT"
}}"""

    doc_for_extract = doc_text[:MAX_DOC_CHARS]
    if len(doc_text) > MAX_DOC_CHARS:
        logger.warning(f"  doc truncated: {len(doc_text)} \u2192 {MAX_DOC_CHARS} chars")

    user_prompt = f"""Document Type (per identifier): {identification.get('document_type')}
Framework: {fw} ({fw_name})

DOCUMENT (with paragraph anchors):
{doc_for_extract}

Extract all fields per Framework {fw}. Return JSON only."""

    try:
        resp = groq_client.chat.completions.create(
            model=EXTRACTOR_MODEL,
            messages=[{"role":"system","content":system},
                      {"role":"user","content":user_prompt}],
            temperature=0.1, max_tokens=6000)
        raw = resp.choices[0].message.content.strip()
        if "</think>" in raw: raw = raw.split("</think>")[-1].strip()
        s, e = raw.find("{"), raw.rfind("}")+1
        extracted = json.loads(raw[s:e]) if s>=0 and e>s else {}
    except Exception as ex:
        logger.error(f"Extractor failed: {ex}")
        extracted = {f: "NOT MENTIONED IN DOCUMENT" for f in fields}

    for f in fields:
        if f not in extracted:
            extracted[f] = "NOT MENTIONED IN DOCUMENT"

    # Hybrid: also extract secondary framework
    secondary = identification.get("secondary_framework")
    if identification.get("is_hybrid") and secondary and secondary in FRAMEWORKS and secondary != fw:
        logger.info(f"  hybrid \u2014 also extracting framework {secondary}")
        secondary_extracted = await extract_framework_fields(
            groq_client, doc_text,
            {**identification, "framework_code": secondary, "is_hybrid": False})
        extracted["_secondary_framework"] = {
            "code": secondary,
            "name": FRAMEWORKS[secondary]["name"],
            "fields": {k: v for k, v in secondary_extracted["fields"].items()
                       if not k.startswith("_")}
        }

    elapsed = int((time.time()-t0)*1000)
    populated = sum(1 for k, v in extracted.items()
                    if not k.startswith("_") and v and v != "NOT MENTIONED IN DOCUMENT")
    logger.info(f"[Agent 3] framework={fw} | {populated}/{len(fields)} populated | {elapsed}ms")
    return {"framework_code": fw, "framework_name": fw_name,
            "fields": extracted, "extract_time_ms": elapsed}


# ══════════════════════════════════════════════════════════════════════════
# AGENT 4 — MODULE RUNNER (Step 3)
# ══════════════════════════════════════════════════════════════════════════

async def run_modules(groq_client, doc_text: str, identification: Dict,
                      extraction: Dict, modules_requested: List[str]) -> Dict[str, Any]:
    t0 = time.time()
    fw = identification["framework_code"]

    # Auto-trigger by framework
    auto = set()
    if fw == "A":   auto.update(["chronology", "issue_wise", "procedural"])
    elif fw == "B": auto.update(["clause_table", "contradictions", "risk", "missing_provisions"])
    elif fw == "C": auto.update(["chronology", "issue_wise", "procedural", "risk"])
    elif fw == "D": auto.update(["chronology"])
    elif fw == "G": auto.update(["chronology"])

    active = sorted(set(modules_requested) | auto)
    logger.info(f"[Agent 4] active modules: {active}")
    results = {}
    doc_for_mod = doc_text[:MAX_DOC_CHARS]

    MODULE_PROMPTS = {
        "chronology": ("Chronology Report",
            'Generate a strict chronological timeline of ALL dates, events, deadlines, and proceedings '
            'mentioned in the document. Each entry: '
            '{"date": "DD/MM/YYYY or as appearing", "event": "what happened", "party_or_authority": "who", "source": "[\u00b6N]"}. '
            'Return JSON array sorted chronologically. Do not invent dates.'),
        "issue_wise": ("Issue-Wise Analysis",
            'Identify all distinct legal issues. Each issue: '
            '{"issue_no": 1, "issue_description": "...", "findings_or_provisions": "...", "outcome_or_risk": "...", "source": "[\u00b6N]"}. '
            'Return JSON array. Issues should be material legal questions, not procedural minutiae.'),
        "clause_table": ("Clause-Level Extraction",
            'For each clause/section/article: '
            '{"clause_no": "X.X", "title": "...", "summary": "10-25 words", "risk_flag": "High/Medium/Low/None", "standard_or_non_standard": "Standard/Non-Standard", "source": "[\u00b6N]"}. '
            'Return JSON array. Summaries from document text only.'),
        "contradictions": ("Contradiction Detection",
            'Identify clauses/statements that contradict each other. Each: '
            '{"clause_a": "[\u00b6X] short excerpt", "clause_b": "[\u00b6Y] short excerpt", "nature_of_conflict": "..."}. '
            'Return JSON array. If no contradictions, return empty array. Do not invent conflicts.'),
        "procedural": ("Procedural Validation",
            'Based ONLY on document text, assess: '
            '(a) Was mandatory notice/hearing given? (b) Is jurisdiction internally consistent? '
            '(c) Are limitation periods facially satisfied? (d) Were statutory procedures followed? '
            'Return JSON object: '
            '{"notice_or_hearing": {"status": "Apparent/Apparent Gap/Cannot Confirm", "note": "...", "source": "[\u00b6N]"}, '
            '"jurisdiction": {...}, "limitation": {...}, "statutory_procedures": {...}}. '
            'Use "VERIFY INDEPENDENTLY" in note for flagged gaps.'),
        "risk": ("Risk Register",
            'From document content, produce risk register entries: '
            '{"risk_no": 1, "risk_description": "...", "severity": "High/Medium/Low", "clause_or_para": "[\u00b6N]", "recommended_attention": "..."}. '
            'Return JSON array. Severity grounded in document language only.'),
        "missing_provisions": ("Missing Standard Provisions",
            'List standard provisions expected for this document type that appear absent: '
            '{"absent_provision": "e.g., Force Majeure Clause", "rationale": "expected because...", "severity": "High/Medium/Low"}. '
            'Return JSON array. Only flag provisions genuinely expected for this document type.'),
    }

    for mod in active:
        if mod not in MODULE_PROMPTS: continue
        title, instruction = MODULE_PROMPTS[mod]
        system = f"""You are running the {title} module on a legal document.

ABSOLUTE RULES:
1. Every output element must trace to [\u00b6N] in the document.
2. Never invent dates, names, amounts, or events not in the document.
3. If silent, state "NOT MENTIONED IN DOCUMENT" or omit gracefully.
4. Output strict JSON only.

INSTRUCTION: {instruction}"""
        user_prompt = f"DOCUMENT (with paragraph anchors):\n\n{doc_for_mod}"
        try:
            resp = groq_client.chat.completions.create(
                model=MODULE_MODEL,
                messages=[{"role":"system","content":system},
                          {"role":"user","content":user_prompt}],
                temperature=0.1, max_tokens=3500)
            raw = resp.choices[0].message.content.strip()
            if "</think>" in raw: raw = raw.split("</think>")[-1].strip()
            parsed = None
            for opener, closer in [("[", "]"), ("{", "}")]:
                s, e = raw.find(opener), raw.rfind(closer)+1
                if s >= 0 and e > s:
                    try:
                        parsed = json.loads(raw[s:e]); break
                    except json.JSONDecodeError: continue
            results[mod] = parsed if parsed is not None else {"error": "Could not parse module output"}
            count = len(results[mod]) if isinstance(results[mod], list) else 1
            logger.info(f"  module {mod}: {count} item(s)")
        except Exception as ex:
            logger.warning(f"  module {mod} failed: {ex}")
            results[mod] = {"error": str(ex)}

    elapsed = int((time.time()-t0)*1000)
    logger.info(f"[Agent 4] {len(results)} module(s) | {elapsed}ms")
    return {"modules": results, "active_modules": active,
            "auto_triggered": sorted(auto), "modules_time_ms": elapsed}


# ══════════════════════════════════════════════════════════════════════════
# AGENT 5 — OUTPUT FORMATTER (Step 4)
# ══════════════════════════════════════════════════════════════════════════

async def format_output(groq_client, doc_text: str, identification: Dict,
                        extraction: Dict, modules: Dict,
                        output_format: str, retry_feedback: str = "") -> str:
    t0 = time.time()
    fw = identification["framework_code"]
    fw_name = identification["framework_name"]
    fmt = output_format if output_format in OUTPUT_FORMATS else "detailed_digest"
    fmt_desc = OUTPUT_FORMATS[fmt]

    parties_str = "; ".join(identification.get("parties", [])) or "NOT MENTIONED IN DOCUMENT"
    applicable_law_str = "; ".join(identification.get("applicable_law", [])) or "NOT MENTIONED IN DOCUMENT"

    identification_block = f"""DOCUMENT TYPE       : {identification.get('document_type')}
ISSUING AUTHORITY   : {identification.get('issuing_authority')}
JURISDICTION        : {identification.get('jurisdiction')}
DOCUMENT DATE       : {identification.get('document_date')}
PARTIES INVOLVED    : {parties_str}
SUBJECT MATTER      : {identification.get('subject_matter')}
APPLICABLE LAW      : {applicable_law_str}
DOCUMENT CONDITION  : {identification.get('document_condition')}"""

    # Compress extraction for prompt
    extraction_lines = []
    for fld, val in extraction["fields"].items():
        if fld.startswith("_"): continue
        if not val or val == "NOT MENTIONED IN DOCUMENT": continue
        val_str = "; ".join(str(v) for v in val[:6]) if isinstance(val, list) else str(val)
        if len(val_str) > 600: val_str = val_str[:600] + "..."
        extraction_lines.append(f"  {fld}: {val_str}")
    extraction_compact = "\n".join(extraction_lines[:40])

    # Module summary
    module_compact = ""
    for mod, mod_data in modules.get("modules", {}).items():
        if isinstance(mod_data, list) and mod_data:
            module_compact += f"\n  [{mod}] {len(mod_data)} items: {json.dumps(mod_data[:3], default=str)[:500]}...\n"
        elif isinstance(mod_data, dict) and "error" not in mod_data:
            module_compact += f"\n  [{mod}] {json.dumps(mod_data, default=str)[:500]}\n"

    format_specific = {
        "one_line_ratio":
            "Output ONLY ONE sentence stating the binding legal proposition. No headers, no preamble. "
            "If document is not a judgment, return: 'One-Line Ratio is not applicable \u2014 this is a [document type], not a judgment.'",
        "executive_summary":
            "Output 5-7 lines: parties, nature of proceeding, key outcome, operative direction. "
            "Plain prose, no headers, no bullets. Each line one sentence.",
        "concise_professional":
            "Output 1-2 paragraphs (200-300 words). Cover parties, issue, outcome/direction, practical implication.",
        "detailed_digest":
            "Output full Detailed Legal Digest with these sections:\n"
            "(1) DOCUMENT IDENTIFICATION (verbatim from input)\n"
            "(2) FRAMEWORK-SPECIFIC ANALYSIS \u2014 each populated field as named heading with content + [\u00b6N]\n"
            "(3) MODULE OUTPUTS \u2014 chronology/issues/contradictions/risks/procedural/missing provisions as applicable\n"
            "(4) DOCUMENT INTEGRITY NOTE \u2014 any quality issues, missing annexures, unclear sections\n"
            "Use markdown headings. Plain prose under each. Reproduce critical findings verbatim with [\u00b6N].",
        "litigation_note":
            "Output Issue \u2192 Argument \u2192 Finding \u2192 Outcome for each major issue. "
            "ISSUE: [issue]; ARGUMENTS: [for/against]; FINDING: [court's conclusion + \u00b6]; OUTCOME: [direction].",
        "issue_wise":
            "Output numbered list of every distinct legal issue. Each: description, finding, outcome, [\u00b6N].",
        "headnote":
            "Output court-publication-style headnote: (1) Catch-words hyphen-separated, "
            "(2) Brief facts (1-2 lines), (3) Holding/Ratio (verbatim if possible), (4) Operative direction. "
            "Strict reporter style. Judgments only.",
        "clause_table":
            "Output markdown table: Clause No | Title | Summary | Risk | Standard?. "
            "Source from clause_table module. If module absent: 'Clause Table not applicable.'",
        "risk_report":
            "Output Risk Register table: Risk No | Description | Severity | Clause/Para | Recommended Attention. "
            "Source from risk module. Add 1-para exec note above table.",
        "chronology":
            "Output chronological timeline as markdown table: Date | Event | Party/Authority | Source. "
            "Source from chronology module.",
        "advisory":
            "Output action-oriented advisory: (1) Compliance Requirements with deadlines from document, "
            "(2) Risk Flags with severity, (3) Recommended Next Steps from document's language only. "
            "End with: 'Independent legal advice recommended before action.'",
        "tabular":
            "Output key data points (parties, dates, amounts, sections) in markdown table: Field | Value.",
    }

    fmt_inst = format_specific.get(fmt, format_specific["detailed_digest"])
    retry_block = (f"\n\n\u26a0 RETRY: Previous attempt failed source-grounding. Fix these issues:\n{retry_feedback}\n"
                   if retry_feedback else "")

    system = f"""You are formatting a legal document analysis into the requested output format.

CRITICAL: Use ONLY the structured analysis provided below. Do not import external facts.
Preserve all [\u00b6N] paragraph anchors from the source analysis.

Format: {fmt} \u2014 {fmt_desc}

FORMAT INSTRUCTIONS:
{fmt_inst}

ABSOLUTE RULES:
- Never invent content not in the analysis below
- Never use banned phrases: "typically", "generally", "in practice", "settled law", "well-settled"
- For operative findings, holdings, orders \u2014 reproduce verbatim with [\u00b6N]
- If the requested format is not applicable to this document type, state so clearly
- Maximum paragraph anchor in document: do not invent paragraph numbers beyond what's provided
{retry_block}"""

    user_prompt = f"""\u2550\u2550\u2550 IDENTIFICATION \u2550\u2550\u2550
{identification_block}

\u2550\u2550\u2550 FRAMEWORK {fw} EXTRACTION ({fw_name}) \u2550\u2550\u2550
{extraction_compact}

\u2550\u2550\u2550 MODULE OUTPUTS \u2550\u2550\u2550
{module_compact or '(no modules activated)'}

Generate the {fmt} output now. Use markdown for structure."""

    try:
        resp = groq_client.chat.completions.create(
            model=FORMATTER_MODEL,
            messages=[{"role":"system","content":system},
                      {"role":"user","content":user_prompt}],
            temperature=0.2, max_tokens=4000)
        output = resp.choices[0].message.content.strip()
        if "</think>" in output: output = output.split("</think>")[-1].strip()
    except Exception as ex:
        logger.error(f"Formatter failed: {ex}")
        output = f"[Formatting failed: {ex}]"

    logger.info(f"[Agent 5] format={fmt} | {len(output)} chars | {int((time.time()-t0)*1000)}ms")
    return output


# ══════════════════════════════════════════════════════════════════════════
# AGENT 6 — SOURCE-GROUNDING VERIFIER (Steps 5+6)
# ══════════════════════════════════════════════════════════════════════════

def verify_source_grounding(output: str, doc_text: str,
                            anchor_map: Dict[int, str]) -> Dict[str, Any]:
    issues = []

    # 1. Paragraph references must exist
    refs = detect_paragraph_refs(output)
    invalid = [r for r in refs if r not in anchor_map]
    if invalid:
        issues.append({"type": "INVALID_PARA_REFS", "severity": "HIGH",
                       "note": f"Output references paragraphs not in document: {invalid[:10]}",
                       "refs": invalid})

    # 2. Banned phrases
    banned = []
    for pat in BANNED_PHRASES:
        for m in re.finditer(pat, output, re.IGNORECASE):
            ctx = output[max(0, m.start()-30):m.end()+30]
            banned.append({"phrase": m.group(0), "context": ctx})
    if banned:
        issues.append({"type": "BANNED_PHRASES", "severity": "MEDIUM",
                       "note": f"{len(banned)} banned hedge phrase(s)",
                       "occurrences": banned[:5]})

    # 3. Settled-law strict ban
    if re.search(r'\bsettled law\b|\bwell[-\s]?settled\b', output, re.IGNORECASE):
        issues.append({"type": "SETTLED_LAW_CLAIM", "severity": "HIGH",
                       "note": "Output claims 'settled law' \u2014 forbidden under Step 6 unless quoted from document."})

    # 4. Inference language
    inference_pats = [
        r"\bthis means that\b", r"\btherefore (?:the court|the authority) would\b",
        r"\bwould likely\b", r"\bmay be expected to\b",
    ]
    inferences = [p for p in inference_pats if re.search(p, output, re.IGNORECASE)]
    if inferences:
        issues.append({"type": "INFERENCE_LANGUAGE", "severity": "MEDIUM",
                       "note": f"Inferential language detected: {inferences}"})

    # 5. Citation invention check
    case_cit_pat = re.compile(
        r'\b([A-Z][A-Za-z&\s\.]{2,40}?\s+v\.\s+[A-Z][A-Za-z&\s,\.]{2,60}?)\s*,?\s*'
        r'((?:\(\d{4}\)|\[\d{4}\])\s*\d+\s*[A-Z]+\s*\d+|'
        r'\d{4}\s*\(\d+\)\s*[A-Z]+\s*\d+|'
        r'\d{4}\s+SCC\s+OnLine\s+[A-Z]+\s+\d+)'
    )
    invented = []
    output_citations = []
    for m in case_cit_pat.finditer(output):
        case_name = m.group(1).strip()
        citation = m.group(2).strip()
        output_citations.append((case_name, citation))
        # Case name first 15 chars should appear in doc_text
        if case_name[:15].lower() not in doc_text.lower():
            invented.append({"case": case_name, "citation": citation})
    if invented:
        issues.append({"type": "INVENTED_CITATIONS", "severity": "CRITICAL",
                       "note": f"{len(invented)} case citation(s) not present in document",
                       "citations": invented[:5]})

    sev_w = {"CRITICAL": 10, "HIGH": 5, "MEDIUM": 2, "LOW": 1}
    penalty = sum(sev_w.get(i.get("severity"), 0) for i in issues)
    score = max(0.0, 1.0 - penalty / 30.0)
    passed = not any(i.get("severity") in ("CRITICAL", "HIGH") for i in issues)
    logger.info(f"[Agent 6] {'PASS' if passed else 'FAIL'} | issues={len(issues)} | score={score:.2f}")
    return {"passed": passed, "issues": issues, "score": round(score, 2),
            "para_refs_used": refs, "para_refs_invalid": invalid,
            "citations_in_output": len(output_citations),
            "citations_invented": len(invented)}


# ══════════════════════════════════════════════════════════════════════════
# PIPELINE
# ══════════════════════════════════════════════════════════════════════════

async def run_summarizer_pipeline(groq_client, doc_text: str, ocr_quality: str,
                                  output_format: str = "detailed_digest",
                                  modules_requested: List[str] = None,
                                  user_instructions: str = "") -> Dict[str, Any]:
    t0 = time.time()
    pi = {"agents_used": [], "retries": 0}
    modules_requested = modules_requested or []

    anchored_text, anchor_map = anchor_document(doc_text)
    logger.info(f"Doc anchored: {len(anchor_map)} paragraphs")

    # [1/6]
    logger.info("[1/6] Identifying document...")
    identification = await identify_document(groq_client, doc_text, ocr_quality)
    pi["agents_used"].append("identifier")
    pi["identification"] = {"type": identification["document_type"],
                            "framework": identification["framework_code"]}

    # [2/6]
    logger.info("[2/6] Inspecting document quality...")
    quality_report = inspect_document_quality(doc_text, ocr_quality)
    pi["agents_used"].append("quality_inspector")
    pi["quality"] = {"ocr_quality": ocr_quality,
                     "issues_count": len(quality_report["issues"])}

    if any(i["type"] == "EXTRACTION_FAILED" for i in quality_report["issues"]):
        return {"success": False,
                "error": "Document extraction failed \u2014 cannot proceed",
                "quality_report": quality_report,
                "disclaimer": DISCLAIMER_TEXT, "pipeline": pi}

    # [3/6]
    logger.info("[3/6] Extracting framework fields...")
    extraction = await extract_framework_fields(groq_client, anchored_text, identification)
    pi["agents_used"].append("extractor")
    pi["extraction"] = {"framework": extraction["framework_code"],
                        "fields_populated": sum(
                            1 for k, v in extraction["fields"].items()
                            if not k.startswith("_") and v and v != "NOT MENTIONED IN DOCUMENT")}

    # [4/6]
    logger.info("[4/6] Running analytical modules...")
    module_results = await run_modules(groq_client, anchored_text, identification,
                                       extraction, modules_requested)
    pi["agents_used"].append("module_runner")
    pi["modules"] = {"active": module_results["active_modules"],
                     "auto_triggered": module_results["auto_triggered"]}

    # [5/6]
    logger.info(f"[5/6] Formatting output ({output_format})...")
    final_output = await format_output(groq_client, anchored_text, identification,
                                       extraction, module_results, output_format)
    pi["agents_used"].append("formatter")

    # [6/6]
    logger.info("[6/6] Verifying source grounding...")
    verification = verify_source_grounding(final_output, doc_text, anchor_map)
    pi["agents_used"].append("verifier")

    # Retry with feedback if grounding failed
    if not verification["passed"] and MAX_RETRY_LOOPS > 0:
        logger.warning(f"  grounding FAILED \u2014 retrying with verifier feedback")
        pi["retries"] += 1
        feedback_str = json.dumps([{"type": i["type"], "note": i["note"]}
                                    for i in verification["issues"]], indent=2)
        final_output_retry = await format_output(
            groq_client, anchored_text, identification, extraction, module_results,
            output_format, retry_feedback=feedback_str)
        verification_retry = verify_source_grounding(final_output_retry, doc_text, anchor_map)
        pi["agents_used"].extend(["formatter_retry", "verifier_retry"])
        if verification_retry["score"] >= verification["score"]:
            final_output = final_output_retry
            verification = verification_retry

    pi["total_time_ms"] = int((time.time() - t0) * 1000)

    # Build Document Integrity Note
    integrity_lines = []
    if ocr_quality not in ("NotOCR", "High"):
        integrity_lines.append(f"OCR Quality: {ocr_quality} \u2014 verify critical figures/dates against original.")
    for issue in quality_report["issues"]:
        if issue["severity"] in ("HIGH", "CRITICAL"):
            integrity_lines.append(f"{issue['type']}: {issue.get('note', '')}")
    if not integrity_lines:
        integrity_lines.append("Document appears clear and complete. No quality issues detected.")
    integrity_note = "\n".join(integrity_lines)

    logger.info(f"DONE: {identification['document_type']} | format={output_format} | "
                f"grounding_score={verification['score']} | {pi['total_time_ms']}ms")

    return {"success": True,
            "identification": identification,
            "framework_used": extraction["framework_code"],
            "framework_name": extraction["framework_name"],
            "extracted_fields": extraction["fields"],
            "modules": module_results["modules"],
            "modules_active": module_results["active_modules"],
            "output_format": output_format,
            "formatted_output": final_output,
            "quality_report": quality_report,
            "verification": verification,
            "document_integrity_note": integrity_note,
            "disclaimer": DISCLAIMER_TEXT,
            "anchor_count": len(anchor_map),
            "pipeline": pi}


# ══════════════════════════════════════════════════════════════════════════
# USER INSTRUCTION PARSER
# ══════════════════════════════════════════════════════════════════════════

def parse_user_command(instructions: str) -> Tuple[str, List[str]]:
    if not instructions: return "detailed_digest", []
    inst_lower = instructions.lower().strip()
    output_format = "detailed_digest"
    modules = []
    for shortcut, action in USER_SHORTCUTS.items():
        if shortcut in inst_lower:
            if action.startswith("_module_"):
                modules.append(action[len("_module_"):])
            else:
                output_format = action
                if action == "chronology": modules.append("chronology")
                elif action == "issue_wise": modules.append("issue_wise")
                elif action == "clause_table": modules.append("clause_table")
                elif action == "risk_report": modules.append("risk")
    if "contradiction" in inst_lower or "conflict" in inst_lower:
        modules.append("contradictions")
    if "missing" in inst_lower and "provision" in inst_lower:
        modules.append("missing_provisions")
    if "procedural" in inst_lower:
        modules.append("procedural")
    return output_format, list(dict.fromkeys(modules))


# ══════════════════════════════════════════════════════════════════════════
# FASTAPI APP
# ══════════════════════════════════════════════════════════════════════════

groq_client = None

@asynccontextmanager
async def lifespan(app):
    global groq_client
    groq_client = Groq(api_key=GROQ_API_KEY)
    logger.info("Groq client initialised")
    logger.info(f"Frameworks: {list(FRAMEWORKS.keys())}")
    logger.info(f"Output formats: {list(OUTPUT_FORMATS.keys())}")
    yield


app = FastAPI(title="Legal Document Intelligence Platform",
              version="2.0.0", lifespan=lifespan)

if TEST_MODE:
    app.add_middleware(CORSMiddleware, allow_origins=["*"],
                       allow_credentials=False, allow_methods=["*"], allow_headers=["*"])
    logger.info("[CORS] Test \u2014 all origins")
else:
    origins = [o.strip() for o in os.getenv("CORS_ORIGINS", "").split(",") if o.strip()]
    if not origins:
        logger.warning("CORS_ORIGINS not set \u2014 defaulting to incometaxlibrary.com")
        origins = ["https://incometaxlibrary.com", "https://www.incometaxlibrary.com"]
    app.add_middleware(CORSMiddleware, allow_origins=origins,
                       allow_credentials=True, allow_methods=["*"], allow_headers=["*"])
    logger.info(f"[CORS] Production \u2014 origins: {origins}")


class SummarizeTextRequest(BaseModel):
    document_text: str = Field(..., min_length=50, max_length=200000)
    user_instructions: str = Field(default="", max_length=2000)
    output_format: Optional[str] = Field(default=None)


@app.post("/api/summarize/text", tags=["Summarize"])
async def summarize_text(req: SummarizeTextRequest):
    if not groq_client: raise HTTPException(503, "Not ready")
    output_fmt, modules = parse_user_command(req.user_instructions)
    if req.output_format and req.output_format in OUTPUT_FORMATS:
        output_fmt = req.output_format
    return await run_summarizer_pipeline(
        groq_client, req.document_text, "NotOCR",
        output_format=output_fmt, modules_requested=modules,
        user_instructions=req.user_instructions)


@app.post("/api/summarize/file", tags=["Summarize"])
async def summarize_file(file: UploadFile = File(...),
                          user_instructions: str = Form(""),
                          output_format: str = Form("")):
    if not groq_client: raise HTTPException(503, "Not ready")
    ext = os.path.splitext(file.filename or "")[1].lower()
    if ext not in (".pdf", ".docx", ".txt"):
        raise HTTPException(400, f"Unsupported file type: {ext}")
    content = await file.read()
    if not content: raise HTTPException(400, "Empty file")
    if len(content) > 20 * 1024 * 1024:
        raise HTTPException(400, "File too large (max 20MB)")

    extractors = {".pdf": extract_text_from_pdf,
                  ".docx": extract_text_from_docx,
                  ".txt": extract_text_from_txt}
    doc_text, ocr_quality = extractors[ext](content)
    if doc_text.startswith("[PDF extraction failed") or doc_text.startswith("[DOCX error"):
        raise HTTPException(400, doc_text)
    if len(doc_text) < 50:
        raise HTTPException(400, f"Extracted text too short ({len(doc_text)} chars)")

    output_fmt, modules = parse_user_command(user_instructions)
    if output_format and output_format in OUTPUT_FORMATS:
        output_fmt = output_format
    result = await run_summarizer_pipeline(
        groq_client, doc_text, ocr_quality,
        output_format=output_fmt, modules_requested=modules,
        user_instructions=user_instructions)
    result["source_file"] = {"filename": file.filename,
                              "size_bytes": len(content),
                              "ocr_quality": ocr_quality,
                              "extracted_chars": len(doc_text)}
    return result


@app.get("/api/summarize/frameworks", tags=["Reference"])
async def list_frameworks():
    return {"frameworks": {k: {"name": v["name"], "applies_to": v["applies_to"],
                                "fields": v["fields"]}
                            for k, v in FRAMEWORKS.items()}}


@app.get("/api/summarize/formats", tags=["Reference"])
async def list_formats():
    return {"output_formats": OUTPUT_FORMATS, "user_shortcuts": USER_SHORTCUTS}


@app.get("/api/summarize/modules", tags=["Reference"])
async def list_modules():
    return {"modules": {
        "chronology": "Date-event timeline (auto for A/C/D/G)",
        "issue_wise": "Numbered legal issues (auto for A/C)",
        "clause_table": "Clause-by-clause extraction (auto for B)",
        "contradictions": "Detect internal conflicts (auto for B)",
        "procedural": "Procedural validation (auto for A/C)",
        "risk": "Risk register (auto for B/C)",
        "missing_provisions": "Standard provisions absent (auto for B)",
    }}


@app.get("/", tags=["System"])
async def root():
    return {"name": "Legal Document Intelligence Platform", "version": "2.0.0",
            "test_mode": TEST_MODE,
            "architecture": "6-Agent closed-world pipeline (no external retrieval)",
            "frameworks": list(FRAMEWORKS.keys()),
            "output_formats": list(OUTPUT_FORMATS.keys()),
            "models": {"identifier": IDENTIFIER_MODEL, "extractor": EXTRACTOR_MODEL,
                       "module": MODULE_MODEL, "formatter": FORMATTER_MODEL,
                       "verifier": VERIFIER_MODEL}}


@app.get("/api/health", tags=["System"])
async def health():
    return {"status": "healthy" if groq_client else "degraded",
            "version": "2.0.0",
            "groq": "ok" if groq_client else "down",
            "test_mode": TEST_MODE}


if __name__ == "__main__":
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument("--host", default="0.0.0.0")
    p.add_argument("--port", type=int, default=5003)
    p.add_argument("--test", action="store_true", help="Test mode (open CORS)")
    args = p.parse_args()
    logger.info("=" * 60)
    logger.info(f"Legal Document Intelligence Platform v2.0 \u2014 {'TEST' if TEST_MODE else 'PRODUCTION'}")
    logger.info(f"6-agent closed-world pipeline")
    logger.info(f"Port: {args.port}")
    logger.info("=" * 60)
    uvicorn.run("summarizer_agent_v2:app", host=args.host, port=args.port, log_level="info")
